#!name= 4 in 1
#!desc= 模块插件重写合集
#!homepage=https://ybnet.ga
#!author=ybnet
#!icon=https://ybnet.ga/IMG/ybnet.png

# 给不喜欢收藏网址的朋友
[URL Rewrite]
# 浏览器google搜索模块 跳转到小火箭模块合集
^https?://www\.google\.com/search\?q=%E6%A8%A1%E5%9D%97.*$ https://ybnet.ga/shadowrocket.html 302


# 浏览器google搜索插件 跳转到loon插件合集
^https?://www\.google\.com/search\?q=%E6%8F%92%E4%BB%B6.*$ https://ybnet.ga/loon.html 302


# 浏览器google搜索重写 跳转到圈X重写合集
^https?://www\.google\.com/search\?q=%E9%87%8D%E5%86%99.*$ https://ybnet.ga/quantumultx.html 302


# 浏览器google搜索sg 跳转到surge模块合集
^https?://www\.google\.com/search\?q=sg.*$ https://ybnet.ga/surge.html 302

[MITM]
hostname= %APPEND% ybnet.ga,www.google.com