#!name=Art Widget
#!desc=Art Widget解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://yfamily.ml
#!author=yqc007
[Script]
ArtWidgetVipCrack=type=http-response,pattern=^https?:\/\/www\.40sishi\.com\/artwidget\/user\/profile$,requires-body=1,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/ArtWidgetVipCrack.js


[MITM]
hostname = %APPEND% www.40sishi.com
