#!name=爱提词
#!desc=爱提词解锁会员
#!homepage=https://ybnet.ga
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/atc.png



[Script]
爱提词=type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,requires-body=1,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/TeleprompterProCrack.js

[MITM] 
hostname = %APPEND% buy.itunes.apple.com
