#!name=Beelinguapp
#!desc=Beelinguapp解锁会员
#!homepage=https://yfamily.ml
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/beelinguapp.png


[Script]
Beelinguapp=type=http-response,pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$,requires-body=1,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/BeelinguappProCrack.js


[MITM] 
hostname = %APPEND% buy.itunes.apple.com
