#!name=不折叠输入法
#!desc=不折叠输入法解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://yfamily.ml
#!author=89996462
[Script]
bzdsrf=type=http-response,pattern=^http[s]?:\/\/api.keyboard.buzhedie.com\/input\/member_info\/,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/bzdsrf.js


[MITM]
hostname = %APPEND% api.keyboard.buzhedie.com
