#!name=蛋啵
#!desc=蛋啵解锁会员
#!homepage=https://yfamily.ml
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/danbo.png


[Script]
蛋啵=type=http-response,pattern=^https:\/\/api-sub\.meitu\.com\/v2\/user\/vip_info_by_group\.json,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/db.js



[MITM] 
hostname = %APPEND% api-sub.meitu.com
