#!name=饭橘减肥
#!desc=饭橘减肥解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://yfamily.ml
#!author=yqc007
[Script]
FunJoyVipCrack=type=http-response,pattern=^https?:\/\/funjoy-api\.aiyouaiyou\.cn\/api\/User\/GetInfoByCode$,requires-body=1,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/FunJoyVipCrack.js



[MITM]
hostname = %APPEND% funjoy-api.aiyouaiyou.cn
