#!name=lUV-万能小组件
#!desc=lUV-万能小组件解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://yfamily.ml
#!author=89996462
[Script]
luv=type=http-response,pattern=^http[s]?:\/\/widgets-api.kaixinyf.cn\/User\/GetInfoByUserCode,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/luv.js



[MITM]
hostname = %APPEND% widgets-api.kaixinyf.cn
