#!name=MOJi辞書
#!desc=MOJi辞書解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://ybnet.ga
#!author=89996462
[Script]
mojics=type=http-response,pattern=^https:\/\/api\.mojidict\.com\/parse\/functions\/getNPrivileges,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/mojics.js


[MITM]
hostname = %APPEND% api.mojidict.com
