#!name=天气提醒
#!desc=天气提醒
#!author=deezertidal
#!icon= https://raw.githubusercontent.com/deezertidal/private/main/icons/lifeindex.png
#!openUrl=https://github.com/deezertidal/private

[Script]
天气提醒 = type=cron,script-path=https://raw.githubusercontent.com/deezertidal/shadowrocket-rules/main/js/tianqi.js,cronexp="0 0 6-21/5 ? * *",wake-system=1,timeout=10,script-update-interval=0,enable=true
