#!name=TouchRetouch
#!desc=TouchRetouch解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/.png
#!homepage=https://ybnet.ga
#!author=89996462
[Script]
TouchRetouch=type=http-response,pattern=^https?:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers\/\$RCAnonymousID%3A\w{32})$,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/TouchRetouch.js


[MITM]
hostname = %APPEND% api.revenuecat.com
