#!name=VN视频剪辑
#!desc=VN视频剪辑解锁会员
#!homepage=https://yfamily.ml
#!author=yqc007
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/vn.png




[Script]
VN视频剪辑=type=http-response,pattern=^https?:\/\/api2\.vlognow\.me\/vn-pay\/api\/v1\/public\/iap\/receipt\/status,requires-body=1,script-path=https://raw.githubusercontent.com/yqc007/QuantumultX/master/VlogNowProCrack.js
[MITM] 
hostname = %APPEND% api2.vlognow.me
