name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy proxy file
        run: |
          curl -O https://raw.githubusercontent.com/rxsweet/proxies/main/sub/v.txt
          mv v.txt proxy.txt
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "action"
          git add proxy.txt
          git commit -m "Update proxy.txt"
          git push
