name: updata
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
jobs:
  userscript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create userscript Directory
        run: |
          mkdir -p userscript
      - name: update
        run: |
          curl -o userscript/chatgpt.user.js ${{ secrets.NONAME }}
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add userscript
          git commit -m "Update" || exit 0
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
