name: updata
on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * *"
jobs:
  copy_proxy_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Create Proxy Directory
        run: |
          mkdir -p proxy
      - name: Copy Proxy File
        run: |
          curl -o proxy/proxy.txt ${{ secrets.NONAME }}
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add proxy
          git commit -m "Update proxy file" || exit 0
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
