name: Auto Update

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v2

      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: deezertidal/sync
          token: ${{ secrets.PAT }}
          ref: master
          path: tmp

      - name: Create folder if
        run: |
          if [ ! -d "rule" ]; then
            mkdir rule
          fi
      - name: File
        run: |
          cp -r tmp/rule/ASN-CN.list rule/
          cp -r tmp/rule/AdvertisingLite.list rule/
          cp -r tmp/rule/Amazon.list rule/
          cp -r tmp/rule/AntiAD.list rule/
          cp -r tmp/rule/AppStore.list rule/
          cp -r tmp/rule/Apple.list rule/
          cp -r tmp/rule/BBC.list rule/
          cp -r tmp/rule/Bahamut.list rule/
          cp -r tmp/rule/BiliBili.list rule/
          cp -r tmp/rule/China.list rule/
          cp -r tmp/rule/ChinaMedia.list rule/
          cp -r tmp/rule/Cloudflare.list rule/
          cp -r tmp/rule/Discord.list rule/
          cp -r tmp/rule/Disney.list rule/
          cp -r tmp/rule/Dropbox.list rule/
          cp -r tmp/rule/Duckduckgo.list rule/
          cp -r tmp/rule/Emby.list rule/
          cp -r tmp/rule/Facebook.list rule/
          cp -r tmp/rule/Fox.list rule/
          cp -r tmp/rule/GitHub.list rule/
          cp -r tmp/rule/Google.list rule/
          cp -r tmp/rule/HBO.list rule/
          cp -r tmp/rule/Hulu.list rule/
          cp -r tmp/rule/Instagram.list rule/
          cp -r tmp/rule/KKBOX.list rule/
          cp -r tmp/rule/Line.list rule/
          cp -r tmp/rule/Microsoft.list rule/
          cp -r tmp/rule/NetEaseMusic.list rule/
          cp -r tmp/rule/Netflix.list rule/
          cp -r tmp/rule/OneDrive.list rule/
          cp -r tmp/rule/PayPal.list rule/
          cp -r tmp/rule/Proxy.list rule/
          cp -r tmp/rule/ProxyMedia.list rule/
          cp -r tmp/rule/Reddit.list rule/
          cp -r tmp/rule/Spotify.list rule/
          cp -r tmp/rule/TIDAL.list rule/
          cp -r tmp/rule/TVB.list rule/
          cp -r tmp/rule/Telegram.list rule/
          cp -r tmp/rule/TikTok.list rule/
          cp -r tmp/rule/Twitter.list rule/
          cp -r tmp/rule/WeChat.list rule/
          cp -r tmp/rule/Weibo.list rule/
          cp -r tmp/rule/Whatsapp.list rule/
          cp -r tmp/rule/Wikipedia.list rule/
          cp -r tmp/rule/YouTube.list rule/
          cp -r tmp/rule/YouTubeMusic.list rule/
          cp -r tmp/rule/ai.list rule/

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sync rule files"
          git push -u origin master
