name: Run Merge

on:
  workflow_dispatch:
  schedule:
    - cron: '25 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install requests
          pip install beautifulsoup4
      - name: Run script
        run: |
          python -c "
          import os
          with open('./rule/1.list', 'r', encoding='utf-8') as f:
            lines = f.readlines()
          new_lines = []
          for line in lines:
            if not line.startswith('#'):
              if '//' in line:
                line = line[:line.index('//')]
              new_lines.append(line.rstrip())
          with open('./rule/ASN-China.list', 'r', encoding='utf-8') as f:
            lines2 = f.readlines()
          new_lines2 = []
          for line in lines2:
            if '//' in line:
              line = line[:line.index('//')]
            new_lines2.append(line.rstrip()) 
          merged_lines_set = set(new_lines2) | set(new_lines)
          merged_lines = [new_lines2[0]] + list(merged_lines_set - {new_lines2[0]})
          merged_lines = list(filter(lambda x: x != '', merged_lines))
          with open('./rule/ASN-CN.list', 'w', encoding='utf-8') as f:
            f.write('\n'.join(merged_lines))
          "
      - name: Commit and push changes
        run: |
          git config --global user.name 'action'
          git config --global user.email 'action@example.com'
          git add -A
          git commit -m 'Update data'
          git push
