name: Run IPCN Python
on:
  workflow_dispatch:
  schedule:
    - cron: '40 * * * *'
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.6.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install requests
        pip install beautifulsoup4
    - name: Run script
      run: |
        python -c '
        import urllib.request
        import re
        import datetime
        url_list = [    "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Extra/ChinaIP.list",    "https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/cncidr.txt",    "https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Region/ChinaIP.list",    "https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt",    "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt",    "https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/Domestic%20IPs.yaml"]
        pattern = re.compile(r"([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}")
        ip_list = []
        for url in url_list:
            with urllib.request.urlopen(url) as f:
                content = f.read().decode("utf-8")
            lines = [line.strip() for line in content.split("\n") if not line.startswith("#") and line.strip()]
            for line in lines:
                match = pattern.search(line)
                if match:
                    ip = "IP-CIDR," + match.group().replace(",", "/") + ",no-resolve"
                    ip_list.append(ip)
        unique_ips = sorted(set(ip_list))
        now = datetime.datetime.now().strftime("%Y%m%d%H%M")
        unique_ips.insert(0, f"# 由ybnet.ga自动维护 {now} ")
        with open("rule/IPs-CN.list", "w") as f:
            for ip in unique_ips:
                f.write(ip + "\n")
        '
    - name: Commit and push changes
      run: |
        git config --global user.name 'action'
        git config --global user.email 'action@example.com'
        git add -A
        git commit -m 'Update data'
        git push
