name: Sync
on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Set git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: blackmatrix7/ios_rule_script
          path: ios_rule_script
      - name: Sync files
        run: |
          rsync -av --delete ios_rule_script/rule/ rule/
          if [[ -n $(git status --porcelain) ]]; then
            git add -A
            git commit -m "Sync"
            git push
          fi
