name: Auto userscript
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v2
        with:
          repository: deezertidal/sync
          token: ${{ secrets.PAT }} 
          ref: master
      - name: Copy files
        run: |
          cp -r userscript1/BiliEnhance.user.js userscript/
          cp -r userscript1/chatgpt.user.js userscript/
          cp -r userscript1/autopage.user.js userscript/
          cp -r userscript1/mediavip.user.js userscript/
          cp -r userscript1/popupblock.user.js userscript/
          cp -r userscript1/translate.user.js userscript/
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sync"
          git push -u origin master
