name: vercel
on:
  workflow_dispatch:
  schedule:
    - cron: '50 * * * *'
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v3
      - name: Clone
        run: |
          git clone https://github.com/deezertidal/deezertidal.github.io temp
      - name: Git
        run: |
          git config --local user.email "action@action.com"
          git config --local user.name "deezertidal"
      - name: Move
        run: |
          cp -Rf temp/* .
          rm -rf temp
      - name: Replace
        run: |
          find . -type f -name "*" -exec sed -i 's/yfamily\.ml/yfamily\.vercel\.app/g' {} +
      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -A
          git commit -m "replace"
          git remote set-url origin https://github.com/deezertidal/deezertidal.github.io.git
          git push -u origin main
